apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
spec:
  type: LoadBalancer
  selector:
    app: movie-app
  ports:
    - protocol: TCP
      port: 80          # External / ELB Port
      targetPort: 5000  # Container Port (IMPORTANT)
