apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: movie-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
